{
 "title": "New dashboard",
 "time": { "from": "2024-07-22T00:00:00.000Z", "to": "2024-08-14T00:00:00.000Z" },
 "panels": [
  {
   "title": "每日來客人數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"customer\"\r\n  )"
    }
   ]
  },
  {
   "title": "每日銷售額",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {},
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"revenue\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "原萃綠茶",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"原萃綠茶\"\r\n  )"
    },
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"品客洋芋片\"\r\n  )"
    },
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"益生菌\"\r\n  )"
    },
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"肉骨湯麵\"\r\n  )"
    }
   ]
  },
  {
   "title": "肉骨湯麵 (當日銷量)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"肉骨湯麵\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "品客洋芋片 (當日銷量)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"品客洋芋片\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "原萃綠茶 (當日銷量)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"原萃綠茶\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "益生菌 (當日銷量)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket100\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"grafana\" and\r\n    r._field == \"益生菌\"\r\n  )\r\n  |> last()"
    }
   ]
  }
 ]
}